site_name: Klemen's second brain
site_description: ""
site_author: "Klemen Kobau"
docs_dir: docs/
repo_name: "KlemenKobau/second-brain"
repo_url: "https://github.com/KlemenKobau/second-brain"
theme:
  name: "material"
  palette:
    scheme: slate
